"""Builds the MuJoCo scene: Franka Panda + deformable shell cup + cube.

The cup is a 2-D MuJoCo *flex* (triangle shell) created with
<flexcomp type="direct" dim="2">, i.e. every mesh vertex is a 3-DOF point mass
and the wall mechanics come from MuJoCo's built-in shell elasticity:

  * elastic2d="both"  -> membrane (in-plane FEM, constant-strain triangles)
                         + bending (discrete quadratic bending energy),
                         both parametrised by Young's modulus, Poisson ratio
                         and the physical wall thickness.
  * integrator="discrete" -> MuJoCo 3.14's integrator that treats the flex
                         stiffness implicitly (solves with M + h^2 K), which is
                         what makes a 1.5 GPa, sub-millimetre shell stable at
                         a 1 ms time step.

The XML is generated (not hand-written) so that every parameter in
cupsim/config.py - including the cube mass of each trial - is applied
consistently. `python -m cupsim.scene` writes models/scene.xml for the
stand-alone MuJoCo `simulate` viewer.
"""
import os
from dataclasses import dataclass

import mujoco
import numpy as np

from .calibration import calibrated_young, mean_edge_length
from .config import Config
from .cup_mesh import make_cup_mesh, CupMesh

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODEL_DIR = os.path.join(ROOT, "models")


def _fmt(v):
    return " ".join(f"{x:.6g}" for x in np.ravel(v))


def cup_mass(mesh: CupMesh, cfg: Config):
    """Mass = shell area * thickness * density."""
    v, t = mesh.vertices, mesh.triangles
    area = 0.5 * np.linalg.norm(np.cross(v[t[:, 1]] - v[t[:, 0]], v[t[:, 2]] - v[t[:, 0]]), axis=1).sum()
    return area * cfg.cup.thickness * cfg.cup.density, area


def scene_xml(cfg: Config, mesh: CupMesh = None):
    c, cb, tk, sm = cfg.cup, cfg.cube, cfg.task, cfg.sim
    mesh = mesh or make_cup_mesh(c.r_bottom, c.r_top, c.height, c.n_theta, c.n_wall, c.n_bottom)
    m_cup, _ = cup_mass(mesh, cfg)
    radius = c.thickness / 2                 # collision half-thickness of the shell
    cx, cy = tk.cup_xy
    solref, solimp = _fmt(c.solref), _fmt(c.solimp)
    h = cb.size / 2
    if c.calibrate_bending:
        E_model, ratio = calibrated_young(c.young, c.poisson, c.thickness, mean_edge_length(mesh))
    else:
        E_model, ratio = c.young, 1.0

    return f"""<mujoco model="panda_cup_scene">
  <!-- AUTO-GENERATED by cupsim/scene.py from cupsim/config.py - do not edit by hand -->
  <include file="panda_cup.xml"/>

  <option timestep="{sm.timestep}" integrator="{sm.integrator}" solver="{sm.solver}"
          cone="{sm.cone}" impratio="{sm.impratio}" iterations="100" tolerance="1e-8"/>
  <size memory="400M"/>
  <statistic center="{cx - 0.1} 0 0.15" extent="0.55"/>

  <visual>
    <headlight diffuse="0.55 0.55 0.55" ambient="0.35 0.35 0.35" specular="0 0 0"/>
    <global azimuth="150" elevation="-20" offwidth="1920" offheight="1080"/>
    <quality shadowsize="4096"/>
    <map force="0.01" znear="0.005"/>
    <scale contactwidth="0.003" contactheight="0.001" forcewidth="0.002"/>
    <rgba contactforce="0.9 0.1 0.1 1" contactfriction="0.1 0.5 1 1"/>
  </visual>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="3072"/>
    <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4"
             rgb2="0.1 0.2 0.3" markrgb="0.8 0.8 0.8" width="300" height="300"/>
    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5" reflectance="0.1"/>
    <material name="cup" rgba="0.80 0.88 0.97 0.40" specular="0.8" shininess="0.8"/>
    <material name="cube" rgba="1.0 0.35 0.10 1"/>
  </asset>

  <worldbody>
    <light pos="0 0 1.5" dir="0 0 -1" directional="true"/>
    <light pos="{cx + 0.5} -0.5 0.8" dir="-0.5 0.5 -0.6" diffuse="0.3 0.3 0.3"/>
    <!-- floor in geom group 1 so that the "bottom" camera can hide it and look up at the cup -->
    <geom name="floor" type="plane" size="0 0 0.05" material="groundplane" group="1"
          priority="2" friction="0.4 0.005 0.0001" solref="{solref}" solimp="{solimp}"/>

    <!-- cameras. Most are attached to invisible mocap "target" bodies that the script moves
         with the cup, so they keep the cup framed while it is lifted. -->
    <camera name="overview" pos="{cx + 0.75} 0.75 0.55" mode="targetbody" target="cup_target" fovy="45"/>
    <body name="cup_target" mocap="true" pos="{cx} {cy} {c.height / 2}">
      <camera name="front"   pos="0.30 0 0.03"      xyaxes="0 1 0 -0.1 0 1" fovy="32"/>
      <camera name="iso"     pos="0.22 0.20 0.17"   mode="targetbody" target="cup_target" fovy="40"/>
      <camera name="bottom"  pos="0 0 -0.20"        xyaxes="0 1 0 1 0 0" fovy="32"/>
      <camera name="section" pos="0.20 -0.12 -0.04" mode="targetbody" target="cup_target" fovy="38"/>
    </body>
    <body name="pad_target" mocap="true" pos="{cx} {cy + c.r_top} {tk.grasp_height}">
      <!-- side view of the +y finger pad: squeeze (normal) and lift (friction) directions both in the image plane -->
      <camera name="contact" pos="0.13 -0.012 0.0" xyaxes="0 1 0 0 0 1" fovy="30"/>
    </body>

    <!-- the cube: same size in every trial, only the mass changes -->
    <body name="cube" pos="{cx} {cy} {radius * 2 + h + 1e-4}">
      <freejoint name="cube"/>
      <geom name="cube" type="box" size="{h} {h} {h}" mass="{cb.mass}" material="cube"
            priority="2" friction="{cb.mu_cup} 0.005 0.0001" solref="{solref}" solimp="{solimp}"/>
    </body>

    <!-- the cup: thin-walled deformable shell, {len(mesh.vertices)} vertices, {len(mesh.triangles)} triangles,
         mass {m_cup * 1000:.2f} g (= area x {c.thickness * 1000:.2f} mm x {c.density:.0f} kg/m^3) -->
    <flexcomp name="cup" type="direct" dim="2" pos="{cx} {cy} {radius}" radius="{radius:.6g}"
              mass="{m_cup:.6g}" material="cup"
              point="{_fmt(mesh.vertices)}"
              element="{' '.join(map(str, mesh.triangles.ravel()))}">
      <!-- physical E = {c.young / 1e9:.3g} GPa; MuJoCo value scaled x{ratio:.3f} so that the shell's bending
           rigidity matches Kirchhoff plate theory at this element size (cupsim/calibration.py) -->
      <elasticity young="{E_model:.6g}" poisson="{c.poisson}" thickness="{c.thickness}"
                  elastic2d="both" damping="{c.damping}"/>
      <contact condim="3" priority="1" friction="{c.mu_finger} 0.005 0.0001"
               solref="{solref}" solimp="{solimp}" selfcollide="none" internal="false"/>
    </flexcomp>
  </worldbody>
</mujoco>
"""


@dataclass
class SceneIds:
    """Handy indices into the compiled model."""
    flex: int
    vert_adr: int
    nvert: int
    cube_body: int
    cube_geom: int
    floor_geom: int
    left_finger: int
    right_finger: int
    hand: int
    tcp_site: int
    grip_act: int
    arm_qadr: np.ndarray
    arm_dadr: np.ndarray
    finger_qadr: np.ndarray
    arm_act: np.ndarray
    cup_mass: float
    cup_target_mocap: int
    pad_target_mocap: int


def build(cfg: Config, write_to=None):
    """Return (model, mesh, ids). The XML is written next to panda_cup.xml so the include resolves."""
    c = cfg.cup
    mesh = make_cup_mesh(c.r_bottom, c.r_top, c.height, c.n_theta, c.n_wall, c.n_bottom)
    xml = scene_xml(cfg, mesh)
    # unique file per process so several trials can be built in parallel
    path = write_to or os.path.join(MODEL_DIR, f"_generated_scene_{os.getpid()}.xml")
    with open(path, "w") as f:
        f.write(xml)
    model = mujoco.MjModel.from_xml_path(path)
    if write_to is None:
        os.remove(path)                 # temporary file, the compiled model is in memory
    return model, mesh, get_ids(model, cfg, mesh)


def get_ids(m, cfg, mesh):
    f = mujoco.mj_name2id(m, mujoco.mjtObj.mjOBJ_FLEX, "cup")
    arm_j = [m.joint(f"joint{i}").id for i in range(1, 8)]
    fing_j = [m.joint("finger_joint1").id, m.joint("finger_joint2").id]
    return SceneIds(
        flex=f,
        vert_adr=int(m.flex_vertadr[f]),
        nvert=int(m.flex_vertnum[f]),
        cube_body=m.body("cube").id,
        cube_geom=m.geom("cube").id,
        floor_geom=m.geom("floor").id,
        left_finger=m.body("left_finger").id,
        right_finger=m.body("right_finger").id,
        hand=m.body("hand").id,
        tcp_site=m.site("tcp").id,
        grip_act=m.actuator("grip").id,
        arm_qadr=np.array([m.jnt_qposadr[j] for j in arm_j]),
        arm_dadr=np.array([m.jnt_dofadr[j] for j in arm_j]),
        finger_qadr=np.array([m.jnt_qposadr[j] for j in fing_j]),
        arm_act=np.array([m.actuator(f"actuator{i}").id for i in range(1, 8)]),
        cup_mass=cup_mass(mesh, cfg)[0],
        cup_target_mocap=int(m.body_mocapid[m.body("cup_target").id]),
        pad_target_mocap=int(m.body_mocapid[m.body("pad_target").id]),
    )


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser(description="Write models/scene.xml (default config) for the simulate viewer")
    ap.add_argument("--mass", type=float, default=0.1, help="cube mass [kg]")
    a = ap.parse_args()
    cfg = Config()
    cfg.cube.mass = a.mass
    out = os.path.join(MODEL_DIR, "scene.xml")
    model, mesh, ids = build(cfg, write_to=out)
    print(f"wrote {out}\n  nq={model.nq} nv={model.nv} cup vertices={ids.nvert} "
          f"cup mass={ids.cup_mass * 1000:.2f} g cube mass={a.mass * 1000:.0f} g")
